flags:
  apex-ast-serializer:
    paths:
      - packages/apex-ast-serializer
    carryforward: true
  prettier-plugin-apex:
    paths:
      - packages/prettier-plugin-apex
    carryforward: true
comment:
  show_carryforward_flags: true
