contact_links:
  - name: Questions & Discussions
    url: https://github.com/dangmai/prettier-plugin-apex/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
